apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnotes-deployment
  namespace: cloudnotes
  labels:
    app: cloudnotes

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloudnotes

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: cloudnotes

    spec:
      containers:
        - name: cloudnotes-app

          image: 641379500030.dkr.ecr.us-east-1.amazonaws.com/cloudnotesapp:38
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              protocol: TCP

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cloudnotes-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: cloudnotes-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: cloudnotes-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudnotes-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudnotes-secret
                  key: DB_PASSWORD

          # Give Spring Boot enough time to finish startup.
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
